assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [HackzillaTicketBundle]
    # java: /usr/bin/java
    # /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java
    # filters:
    #     cssrewrite: ~
    filters:
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
